#ifndef GLOBALTOOLS_GLOBAL_H
#define GLOBALTOOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GLOBALTOOLS_LIBRARY)
#  define GLOBALTOOLS_EXPORT Q_DECL_EXPORT
#else
#  define GLOBALTOOLS_EXPORT Q_DECL_IMPORT
#endif

#endif // GLOBALTOOLS_GLOBAL_H
